# Motivation: Running a function on data


<b>Vocabulary</b>
<ul>
    <li>list</li>
    <li>element</li>
    <li>index</li>
    <li>slice</li>
    <li>boolean</li>
    <li>package</li>
    <li>numpy</li>
</ul>

# Lists

You can now use Python as a calculator, but it's more useful than a handheld calculator only when you have lots of numbers to work with. You can store a group of numbers, or groups of other things, in a type called a `list`. 

A list is a collection of things (they can have any type, including `int`s, `float`s, `str`s. They are separated by commas and bracketed with square brackets (`[` and `]`), like this: 
```python
shopping_list = ['apple', 'banana', 'cherry']
```

Each individual thing in a list is called an <b>element</b> of that list.

Can a few people tell us their heights? We can create a list of these heights, and print the list: 

In [6]:
shopping_list = ['apple', 'bananas', 'cherries']


With these heights, we've created data! Lists are a common way to store data, because they give us a way to order numbers. A list is just like a single column in a spreadsheet.

Many times you'll want to check how many elements are in your list, which you do with the `len` function, like this: 
```python
len(class_heights)
```
Try that in the cell below: 

In [7]:
class_heights = [72, 72, 64, 65, 66]
print(class_heights)

[72, 72, 64, 65, 66]


In [8]:
len(class_heights)


5

Python has a _function_ for taking the `sum` of the numbers in a list. Let's take the sum of the heights with the following command: 
```python
sum(class_heights)
```
### Example 1: Sum of a list

How many inches tall would our class be if we all stood one on top of each other (take the sum of the heights)? Store the answer in a variable with a sensible name (remember guidelines from above!), and print the result: 

In [9]:
sum(class_heights)

339

*** 

## Adding items to a list

Let's say someone new transferred into the class, and you want to add their height to the `class_heights` list. We can do that with the `append` function, which you call like this:
```python
new_height = 65
class_heights.append(new_height)
print(class_heights)
```
In the second line, `class_heights` is the list that we're _appending_ a new number to, `.append()` says to append the number in parentheses onto `class_heights`.

Copy and paste the code above into the cell below **and execute the cell once**, to see the output.

In [34]:
new_height = 65
class_heights.append(new_height)
print(class_heights)

len(class_heights)


[72, 72, 64, 65, 66, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65]


30

In [58]:
class_heights = [72, 72, 64, 65, 66, 65]

len(class_heights)

6

### Example 2:

What would happen if you executed the cell above a second time? Try it and check your answer.

## List indexing and slicing

Often you'll want to be able to take a single *element*, or a few elements out of a list. To do that, you do what we call *indexing* or *slicing*. 

Let's work with a list using your name rather than `class_heights`.

To get a specific element from the list `full_name`, we put square brackets next to the name of the list, and we put the _index_ of the element that we want inside the brackets. The index starts at **zero for the first element**, one for the second element, etc.: 
```python
first_element = full_name[0]
print(first_element)
```

To help you remember, that python starts at 0 (so the first element is indexed by 0):
```python
# Index =   0    1    2    3    4    5    6    7    8 
astr192 = ['Y', 'U', 'P', 'R', 'A', '2', '0', '2', '4']
```

### Example 3: Zero-based indexing

1. Type your full name in a string, store it in the variable `full_name`
2. You can cast that string into a list of strings by doing this: 
```python
full_name = "YUPRA"
name_list = list(name)
print(name_list)
```
which yields `['Y', 'U', 'P', 'R', 'A']`. Do this to make a list out of your name.
3. Get the second letter in your name using indexing.

In [60]:
my_name = ['T', 'O', 'B', 'I', 'N', ' ', 'W', 'A', 'I', 'N', 'E', 'R']

len(my_name)

12

In [61]:
my_name[0]

'T'

In [62]:
my_name[len(my_name) - 1]

'R'

In [63]:
my_name[-1]

'R'

In [1]:
# Set your full name to a variable, and make that variable into a list

In [ ]:
# Get the second letter in your name

In [64]:
my_name[1]

'O'

What happens if you ask for the 100th element of the list (the 100th letter in your name)?

In [65]:
my_name[100]

IndexError: list index out of range

In [70]:
my_name[0]

['T', 'O', 'B', 'I', 'N', ' ', 'W', 'A', 'I', 'N', 'E', 'R']

### Give me everything starting from

Sometimes you might want to select multiple elements of a list, rather than just one. You can get all elements starting with, for example, the third element by doing `name_list[2:]`. Try getting all the letters in your name starting from the second letter in your name.

In [2]:
# Get every letter in your name starting from the second letter in your name

In [71]:
my_name[2:]

['B', 'I', 'N', ' ', 'W', 'A', 'I', 'N', 'E', 'R']

### Give me everything up to

In the opposite case, you can get every element of a list up to (but not including) an element by putting the index of the element you want everything up to after the colon, like so: `name_list[:5]` gives me all the letters of my name, up to (but not including) the sixth letter in my name. Try getting all the letters in your name up to but not including the tenth letter of your name.

In [72]:
# Get every letter in your name up to the tenth letter in your name with slicing

my_name[:5]

['T', 'O', 'B', 'I', 'N']

In [73]:
my_name[:len(my_name)]

['T', 'O', 'B', 'I', 'N', ' ', 'W', 'A', 'I', 'N', 'E', 'R']

In [75]:
my_name[:-2]

['T', 'O', 'B', 'I', 'N', ' ', 'W', 'A', 'I', 'N']

### Give me everything starting from and up to

You can combine the above two statements to get a range of elements in a list. Try getting the letters in your name starting from the second letter in your name up to (but not including) the fourth letter of your name.

In [ ]:
# Get every letter in your name starting from the second letter up to tenth letter with slicing

In [ ]:
start_second_letter : end_fourth_Letter

In [77]:
my_name[1:4]

['O', 'B', 'I']

In [80]:
number_lists = [ 1, 2,3,4,5,6,7] 

number_lists[2:6]

[3, 4, 5, 6]

# Python packages


We do specialized tasks in Python with <b>package</b>. A package is a collection of Python functions that someone wrote and bundled together for you to use. Some of the Python packages that we'll learn to use include: 

| Package | Uses                     |
|---------|--------------------------|
| `numpy` | Math with arrays (more on this below) | 
| `scipy` | A math toolkit built for use by scientists | 
| `matplotlib` | Visualization (plotting!) | 
| `astropy` | Astronomy-specific functions of all kinds | 

## Numpy

Numpy is the most important package that we're going to teach you about, because it allows you to do calculations very quickly with Python. Below, we'll discover why it's useful.

*** 

Let's say you want to take the _sine_ or _cosine_ of an angle. There are numpy function that do this for you. 

To gain access to numpy's functions, you always need to do this command first: 
```python
import numpy as np
```
Run the line above in the cell below: 

In [81]:
import numpy as np

In [83]:
import numpy as np

Now there's a _package_ stored in the variable called `np` that we can access anywhere in this notebook. There are <b>functions</b> for $\sin$ and $\cos$ that live within numpy. The way to access a function within a package is by calling the package name with a period after it, then the name of the function you want. So for $\sin$, you can do: 
```python
np.sin(0)
```
The `np.` part says "give me this function from numpy". The `sin()` part says "the function that I want to use is $\sin$", and the `0` is the angle that we want to take the $\sin$ of, in units of radians.

In [84]:
np.cos(0)

np.float64(1.0)

Numpy also has some built-in numbers that you might use. For example, $\pi$ is stored (to high precision!), in `np.pi`. Print out numpy's $\pi$ in the cell below: 

In [85]:
np.pi

3.141592653589793

Now let's say you had a list of angles, like `angles`$= [0, \pi/2, \pi, 3\pi/2, 2\pi]$. You could call `np.sin(angles[0])` to get the $\sin$ of the first angle, then `np.sin(angles[1])` on the second angle, etc. But that would be a really slow way to do it! 

### Arrays

The quick way is to create a <b>numpy array</b>. A numpy array is a vector or matrix of numbers, similar to the built in Python lists we saw in the last lesson. ```numpy``` can act on arrays more efficiently than Python can with ordinary lists.

Let's make a numpy array filled with the angles above:
```python
# First, here's the list that we want to have an array of: 
angle_list = [0, 1/2 * np.pi, np.pi, 3/2 * np.pi, 2 * np.pi]

# Here's how we make a numpy array out of the list
angle_array = np.array(angle_list)
```
Write out those lines in the cell below. 

In [91]:
angle_list = [0, 1/2 * np.pi, np.pi, 3/2 * np.pi, 2 * np.pi]

angle_array = np.array(angle_list)

type(angle_array)

numpy.ndarray

In [41]:
angle_list = [0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi]
print(angle_list)

[0, 1.5707963267948966, 3.141592653589793, 4.71238898038469, 6.283185307179586]


In [43]:
angle_array = np.array(angle_list)
print(angle_array)

[0.         1.57079633 3.14159265 4.71238898 6.28318531]


In [92]:
angle_array + 2

array([2.        , 3.57079633, 5.14159265, 6.71238898, 8.28318531])

In [93]:
angle_array / 2

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265])

In [49]:
print(type(angle_list))

<class 'list'>


In [50]:
print(type(angle_array))

<class 'numpy.ndarray'>


In [94]:
print(len(angle_array))

5


In [95]:
print( angle_array[2] )

3.141592653589793


In [53]:
print( angle_array * 2 )

[ 0.          3.14159265  6.28318531  9.42477796 12.56637061]


Let's break down the command `np.array(angle_list)`. The `np.` says we're going to use a function from numpy, the `array()` says we're going to make an array out of the thing in the parentheses, and the `angle_list` is the _input_ or the <b>argument</b> of the function.

The reason you want to put your data into an array, is because it's much easier to do math with arrays than with lists, for example:

In [ ]:
print(angle_list / 2)

In [ ]:
print(angle_array / 2)

In [98]:
my_name_array = np.array(my_name)

print(my_name_array)

['T' 'O' 'B' 'I' 'N' ' ' 'W' 'A' 'I' 'N' 'E' 'R']


### Example 4: Calculations with arrays

What is the $\sin$ and $\cos$ of each angle? Use the numpy array `angle_array` as the argument to the `np.sin` and `np.cos` functions in the cell below:

In [54]:
print(angle_array)

[0.         1.57079633 3.14159265 4.71238898 6.28318531]


In [99]:
np.cos( angle_array )

array([ 1.0000000e+00,  6.1232340e-17, -1.0000000e+00, -1.8369702e-16,
        1.0000000e+00])

Now you might be saying - wait a minute, $\sin(3\pi/2) = 0$, not $\approx$`1e-16`, what's that about? The short answer is - computers often get very very close to approximating the numbers that we actually want, but not all of the way there. You can get better precision if you tell the computer to use more memory. 

## More numpy commands

Now you can do things with the numpy array that you couldn't do with a Python list. 
```python
# Sum of all elements in the array:
np.sum(angle_array)

# Mean of all elements in the array:
np.mean(angle_array)

# Maximum of the elements in the array:
np.max(angle_array)

# Minimum of the elements in the array: 
np.min(angle_array)

# Standard deviation of the elements in the array: 
np.std(angle_array)
```
Try running each of the above commands one-by-one in the cell below to see what they output.

In [113]:
class_heights_array = np.array(class_heights)

print(np.mean(class_heights_array))
print(np.median(class_heights_array))

67.33333333333333
65.5


### Syntax Tips and Help ###
So what happens when you forget the name of a `numpy` function, or the how to use a particular function? `Jupyter` has some cool built-in features that you should take advantage of!

For example, say you forgot the name of the `sum` function -- you can type `np.` and then press `tab`, and you'll see that the notebook lists what functions are available in `numpy`! Spoiler alert, it's a loooong list since `numpy` has many functionalities. 

The point is you can use the `tab` tool (recall tab completion trick) to help you remember or recognize the function you're looking for. 

Just like how in `bash` environments you can read details on how to use a function with `man FUNCTIONNAME`, you can do that in `Python` as well. For example, say you forgot how to use the `np.sin` function -- you can type `np.sin?` + `Ctrl`+`return` and the notebook will return an inline window that tells you almost everything you need to know about the function. 

Try playing around with `np.` + `tab` and `np.cos?`, or any function with a `?` at the end, below.

In [100]:
np.sin?

Call signature:  np.sin(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'sin'>
File:            ~/miniconda3/lib/python3.12/site-packages/numpy/__init__.py
Docstring:      
sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Trigonometric sine, element-wise.

Parameters
----------
x : array_like
    Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original v

## Array arithmetic

There are lots of situations where you'll want to create a certain kind of array, and numpy has functions to help. 

You can make an array of consecutive integers from zero to nine with the function `np.arange`:
```python
consecutive_integers = np.arange(10)
```
Just like with indexing to some endpoint, you tell python what number you want it to stop before.

In [105]:
np.arange(0,10,3)

array([0, 3, 6, 9])

Check it out, numpy did all the work for me, I didn't have to write down all the integers.

Now, this function is very flexible. You can give it 3 <b>arguments</b> instead of 1 and those 3 numbers will signify `np.arange(start, stop, step)`. For example, `np.arange(1, 9, 2)` would start at 1, stop before 9, with a step size of 2 (giving you every second number), so it would return `[1, 3, 5, 7]

Type:        module
String form: <module 'scipy.optimize' from '/Users/tobinw/miniconda3/lib/python3.12/site-packages/scipy/optimize/__init__.py'>
File:        ~/miniconda3/lib/python3.12/site-packages/scipy/optimize/__init__.py
Docstring:  
Optimization and root finding (:mod:`scipy.optimize`)

.. currentmodule:: scipy.optimize

.. toctree::
   :hidden:

   optimize.cython_optimize

SciPy ``optimize`` provides functions for minimizing (or maximizing)
objective functions, possibly subject to constraints. It includes
solvers for nonlinear problems (with support for both local and global
optimization algorithms), linear programming, constrained
and nonlinear least-squares, root finding, and curve fitting.

Common functions and objects, shared across different solvers, are:

.. autosummary::
   :toctree: generated/

   show_options - Show specific options optimization solvers.
   OptimizeResult - The optimization result returned by some optimizers.
   OptimizeWarning - The optimization en

In [ ]:
np.array([0,1,3])

In [107]:
my_name_array[np.array([0,1,3])]

array(['T', 'O', 'I'], dtype='<U1')